### ISSUE TITLE
User story 1: Information on Common Mental Health Issues

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/Awareness#1]
As an Regular Person, I want to find information on recognizing the signs and symptoms of mental health problems so that I can determine if I am experiencing a mental health problem.

**Acceptance Criteria:** 
- [ ] there should be a page dedicated to containing information on recognizing the signs and symptoms of mental health problems.
- [ ] The content should cover signs and symptoms of common mental health issues
- [ ] The content should be brief but contain links to further information
- [ ] The page utilises the Bootstrap components to create a consistent and responsive layout

**Task:**
- [ ] Create a responsive information page featuring a variety of common mental health issues
- [ ] provide buttons linking to further information
