### ISSUE TITLE
User Story 2: Resources/ Seek Help

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/Awareness#2]
As an Individual Seeking Help, I want to access online therapy sessions, support groups and suitable resources so that I can receive professional help and connect with others who share similar experiences.

**Acceptance Criteria:**
- [x] Provide resources so individuals in need can find the help they need
- [x] Link trustworthy and useful external resources
- [x] use bootstrap components to create clickable cards with related image and brief information about each link

**Task:**
- [x] Use bootstrap components to make a responsive and clear section for external resources
