### ISSUE TITLE
User Story 4: Further Inquiry Form

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/Awareness#4]
As an Individual Seeking Help I want to chat with someone to ask for guidance and advice, so I could further understand how to seek professional help and what kind of help might be suitable for me.

**Acceptance Criteria:**
- [x] An inquiry form with fields to fill out personal information and a simple message
- [x] All fields on the form must be completed before the user can submit the form
- [x] When the form is completed correctly, the user is notified by a modal
- [x] Form should be easy to find and accessible on all pages

**Task:**
- [x] Create an inquiry form
- [x] Implement HTML validation on the form to fit the requirements above
- [x] Create a modal notifying successful submission of the form
