### ISSUE TITLE
User Story 5: Prevention/Awareness

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/Awareness#5]
As a Family Member I want to learn how to practice self-care/care for people around me to prevent mental health issues, and to understand early signs of mental health issues to prevent them from worsening

**Acceptance Criteria:**
- [x] Has a section dedicated to prevention/awareness of mental health issues
- [x] Has embedded video introducing mental health issue prevention

**Task:**
- [x] Create a section about mental health issue prevention/awareness with embedded video
