### ISSUE TITLE
User Story 6: Hero Section

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/Awareness#6]
As a User I want to see high-quality image that evokes a sense of calm and well-being, paired with a clear and concise headline that immediately informs me about the website’s purpose

**Acceptance Criteria:**
- [x] Homepage features high-quality image of welcoming feeling
- [x] Provide a precise and simple description of our purpose

**Task:**
- [x] Choose a suitable image as the hero image
- [x] Embed the precise descriptions for the website's purpose within the image
- [x] Design and implement a homepage layout that prominently features the image and descriptions
