### ISSUE TITLE
User Story 8: Events

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/Awareness#8]
As an Individual Seeking Help I want to find events regarding mental health, so I can get to know and connect with others with the same situation or people that can help me. 

**Acceptance Criteria:**
- [ ] Display crucial information of the events and include simple descriptions of event holders and the contents of the events
- [ ] Display images representative of the events to give basic feel of the events
- [ ] Directly link to the event holder's website so they can find further information

**Task:**
- [ ] Use Bootstrap card component to create clickable cards regarding events for mental health issues
- [ ] Make sure the cards are responsive and link to corresponding websites
